# Generated by Django 3.1.2 on 2020-10-03 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('code', models.CharField(blank=True, max_length=8)),
                ('date', models.DateField(auto_now_add=True)),
                ('counter', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Enlaces'
            }
        ),
    ]
